services:
  postgres:
    image: postgres:16-alpine
    container_name: redislab-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: redislab
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: redislab-redis
    ports:
      - "6379:6379"

volumes:
  pgdata:
